#!/bin/bash

#SBATCH --job-name=vmc

#SBATCH -p heavy
#SBATCH --ntasks 8

# #SBATCH --nodes 1
# #SBATCH --account=...

#SBATCH --output=output_file
#SBATCH --error=slurm-%j.err

module purge
module load openmpi/1.10.7

# SLURM_JOB_ID is printed to run_info file in run_slurm.sh
echo "SLURM_NODELIST = $SLURM_NODELIST" >> run_info

# run modes: vmc_mov1_mpi, dmc_mov1_mpi1, dmc_mov1_mpi2, dmc_mov1_mpi3
mpirun $HOME/programs/CHAMP/qmc/champ_mpi.exe -m vmc_mov1_mpi -i input_file

