#!/bin/bash

#SBATCH --job-name=vmc

#SBATCH -p orfoz
#SBATCH --ntasks 55
#SBATCH --time=2-23:50:00

#SBATCH --nodes 1

#SBATCH -C weka

#SBATCH --output=output_file
#SBATCH --error=slurm-%j.err

module purge # remove any modules that were loaded on the client server
module load lib/openmpi/5.0.0

# SLURM_JOB_ID is printed to run_info file in run_slurm.sh
echo "SLURM_NODELIST = $SLURM_NODELIST" >> run_info

# run modes: vmc_mov1_mpi, dmc_mov1_mpi1, dmc_mov1_mpi2, dmc_mov1_mpi3
mpirun -np 55 $HOME/programs/CHAMP/qmc/champ_mpi.exe -m vmc_mov1_mpi -i input_file

